# Generated by Django 2.1.3 on 2019-12-03 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Busy',
            fields=[
                ('id_busy', models.AutoField(db_column='ID_busy', primary_key=True, serialize=False)),
                ('field_bool_field', models.BooleanField(blank=True, db_column='_bool_', null=True)),
            ],
            options={
                'db_table': 'Busy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id_country', models.IntegerField(db_column='ID_country', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Country',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id_film', models.IntegerField(db_column='ID_film', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('specification', models.TextField(blank=True, null=True)),
                ('duration', models.TimeField()),
                ('rental_start_date', models.DateField(blank=True, null=True)),
                ('rental_end_date', models.DateField(blank=True, null=True)),
                ('id_country', models.ForeignKey(db_column='ID_country', on_delete=django.db.models.deletion.DO_NOTHING, to='cinema_theater.Country')),
            ],
            options={
                'db_table': 'Film',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id_room', models.IntegerField(db_column='ID_room', primary_key=True, serialize=False)),
                ('number_of_rows', models.IntegerField()),
                ('number_of_seats', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Room',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id_seance', models.IntegerField(db_column='ID_seance', primary_key=True, serialize=False)),
                ('field_date_field', models.DateField(db_column='_date_')),
                ('field_time_field', models.TimeField(db_column='_time_')),
                ('id_film', models.ForeignKey(db_column='ID_film', on_delete=django.db.models.deletion.DO_NOTHING, to='cinema_theater.Film')),
                ('id_room', models.ForeignKey(db_column='ID_room', on_delete=django.db.models.deletion.DO_NOTHING, to='cinema_theater.Room')),
            ],
            options={
                'db_table': 'Seance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id_seats', models.AutoField(db_column='ID_seats', primary_key=True, serialize=False)),
                ('field_rows_field', models.IntegerField(db_column='_rows_')),
                ('seats', models.IntegerField()),
            ],
            options={
                'db_table': 'Seats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id_style', models.IntegerField(db_column='ID_style', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Style',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.AutoField(db_column='ID_ticket', primary_key=True, serialize=False)),
                ('date_of_sale', models.DateTimeField()),
                ('id_seance', models.ForeignKey(db_column='ID_seance', on_delete=django.db.models.deletion.DO_NOTHING, to='cinema_theater.Seance')),
                ('id_seats', models.ForeignKey(db_column='ID_seats', on_delete=django.db.models.deletion.DO_NOTHING, to='cinema_theater.Seats')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Ticket',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='film',
            name='id_style',
            field=models.ForeignKey(db_column='ID_style', on_delete=django.db.models.deletion.DO_NOTHING, to='cinema_theater.Style'),
        ),
        migrations.AddField(
            model_name='busy',
            name='id_room',
            field=models.ForeignKey(db_column='ID_room', on_delete=django.db.models.deletion.DO_NOTHING, to='cinema_theater.Room'),
        ),
        migrations.AddField(
            model_name='busy',
            name='id_seance',
            field=models.ForeignKey(db_column='ID_seance', on_delete=django.db.models.deletion.DO_NOTHING, to='cinema_theater.Seance'),
        ),
        migrations.AddField(
            model_name='busy',
            name='id_seats',
            field=models.ForeignKey(db_column='ID_seats', on_delete=django.db.models.deletion.DO_NOTHING, to='cinema_theater.Seats'),
        ),
        migrations.AlterUniqueTogether(
            name='busy',
            unique_together={('id_seats', 'id_seance', 'id_room')},
        ),
    ]
